using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace DP.Base
{
    public static class VersionResource
    {
        public static string ReadEmbeddedResource(string assemblyName, string filename)
        {
            try
            {
                //  NOTE: this resource is generated by pre-build step of DP.Base (writing version.txt) and then including file as Embedded Resource
                var asm = Assembly.Load(assemblyName);

                var content = string.Empty;
                using (var stream = asm.GetManifestResourceStream(filename))
                using (var reader = new StreamReader(stream))
                {
                    content = reader.ReadToEnd();
                }

                return content;
            }
            catch (Exception /*ex*/)
            {
                // NOTE: not sure how to log from here
                return null;
            }
        }

        public static List<string> GetVersionStrings()
        {
            //  NOTE: this resource is generated by pre-build step of DP.Base (writing version.txt) and then including file as Embedded Resource
            var content = ReadEmbeddedResource("DP.Base", "DP.Base.version.txt");
            if (string.IsNullOrWhiteSpace(content))
            {
                return null;
            }

            var lines = content.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(e => e.Trim())
                .ToList();
            return lines;
        }
    }
}
